apiVersion: apps.edgenet.io/v1alpha
kind: SelectiveDeployment
metadata:
  name: ping-me-example
  namespace: athena-rc
spec:
  workloads:
    daemonset:
      - apiVersion: apps/v1
        kind: DaemonSet
        metadata:
          name: ping-source
          namespace: athena-rc
          labels:
            app: ping-source
        spec:
          selector:
            matchLabels:
              app: ping-source
          template:
            metadata:
              labels:
                app: ping-source
            spec:
              tolerations:
                - key: node-role.kubernetes.io/master
                  operator: Exists
                  effect: NoSchedule
              containers:
                - name: ping-source
                  image: alpine
                  command: ['/bin/ping']
                  args: ['google.com']
                  resources:
                    limits:
                      cpu: 50m
                      memory: 50Mi
                    requests:
                      cpu: 50m
                      memory: 50Mi
              terminationGracePeriodSeconds: 0
  selector:
    - value:
        - North_America
      operator: In
      quantity: 2
      name: Continent
    - value:
        - Europe
      operator: In
      quantity: 2
      name: Continent
