# role_binding-ath-admin-george.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: athena-rc
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: georgekouk29702970@gmail.com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edgenet:tenant-admin
#  name: edgenet:tenant-collaborator 
