# selectivedeployment.yaml
apiVersion: apps.edgenet.io/v1alpha
kind: SelectiveDeployment
metadata:
  name: cdn-deployment
  namespace: athena-rc
spec:
  workloads:
    deployment:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: cdn-server
          namespace: athena-rc
          labels:
            app: cdn-server
        spec:
          replicas: 4
          selector:
            matchLabels:
              app: cdn-server
          template:
            metadata:
              labels:
                app: cdn-server
            spec:
              tolerations:
                - key: node-role.kubernetes.io/master
                  operator: Exists
                  effect: NoSchedule
              containers:
                - name: cdn-server
                  #image: busybox
                  image: emamatas/appserver
                    #command: ['/bin/sh', '-c', 'sleep infinity']
                  ports:
                    - containerPort: 80
                      protocol: TCP
                    - containerPort: 8080
                      protocol: TCP
                  resources:
                    limits:
                      cpu: 50m
                      memory: 50Mi
                    requests:
                      cpu: 50m
                      memory: 50Mi
              terminationGracePeriodSeconds: 0
  selector:
    - value:
        - Europe
        - Asia
        - North_America
      operator: In
      quantity: 3
      name: Continent
---
apiVersion: v1
kind: Service
metadata:
  name: cdn-service
  namespace: athena-rc
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: vlc
    port: 8080
    targetPort: 8080
  selector:
    app: cdn-server
